
public enum MinionName {

    KAMANDARE_FARS, SHAMSHIRZANE_FARS, NEYZEDARE_FARS, ASBSAVARE_FARS, PAHLEVANE_FARS, SEPAHSALARE_FARS,
    KAMANDARE_TOORANI, GHOLLABSANGDARE_TOORANI, NEYZEDARE_TOORANI, JASOOSE_TOORANI, GORZDARE_TOORANI, SHAHZADEYE_TOORANI,
    DIVE_SIAH, GHOOLE_SANGANDAZ, DIVE_GORAZSAVAR, GHOOLE_BOZORG, GHOOLE_BOZORG2, GHOOLE_DOSAR, SHAHGHOOL,
    OGHAB, MARE_SAMMI, EJDEHAYE_ATASHANDAZ, SHIRE_DARANDE, MARE_GHOOLPEIKAR, GORGE_SEFID, PALANG, GORG, GORAZE_VAHSHI,
    PIRAN, GIV, BAHMAN, ASHKBOOS, IRAJ, SIAVASH, NANESARMA, FOOLADZERE, JADOOGAR, JADOOGAR_AZAM, JEN,
}
