public enum SpellName {
    TOTAL_DISARM, AREA_DISPEL, EMPOWER, FIREBALL, GOD_STRENGTH, HELLFIRE, LIGHTING_BOLT, POISON_LAKE, MADNESS, ALL_DISARM, ALL_POISON, DISPEL,
    HELATH_WITH_PROFIT, GHAZA_BOKHOR_JOON_BEGIRI, ALL_POWER, ALL_ATTACK, WEAKENING, SACRIFICE, KINGS_GUARD, SHOCK

}
